export const POST_CREATED = 'POST_CREATED';
export const POST_CREATING = 'POST_CREATING';
export const POST_CREATION_ERROR = 'POST_CREATION_ERROR';
export const POST_UPDATED = 'POST_UPDATED';
export const POST_UPDATING = 'POST_UPDATING';
export const POST_UPDATING_ERROR = 'POST_UPDATING_ERROR';